### ISSUE TITLE
Very nice design, but lacks sufficient cooling area for 5G

### ISSUE THREAD

**Issue by mlinuxguy** [themainframe/5g-m2-usb3-interface-pcb#1]
I've been playing with 5G modems for my home internet and have various USB 3.0 M.2 sleds that I've tried.  Your design is one of the better ones I've seen with the extra power supply port (5G modems eat up electrons).

Because of all the heat generated by these modems there needs to be sufficient space under the M.2 connector to put a heatsink under the modem like:  icepc M.2 2280 SSD Pure Copper Heatsink Kit Cooler Heat Sink with Silicone Based Thermal Pad for Cooling M.2 SSD NGFF NVME SSD(70x20x2mm)

I suspect a taller M.2 connector would allow such a heatsink.   The WG1608 router has that along with a large copper plane on the PCB directly under the modem.  In my testing having the PCB plane + heat-sink under and on top of the modem keeps it about 5-7C cooler than just on the top of the modem.

I did some quick searches and its likely an option would be a vertical M.2 connector option.  Though bulky it would allow plenty of cooling.

**Comment by themainframe** [comment]
Thanks for the feedback, glad you like the design! I'm not convinced a heatsink fitted *under* the modem (other than the interface PCB itself) is really called for though. I didn't see any implementations where the module had a heatsink fitted *underneath*. Quectel's app note for the RM500Q-GL says the following:

> Add as many ground vias as possible on PCB.
> It is NOT recommended to apply solder mask on the main PCB where the module’s thermal
dissipation area is located.

The 3 ground layers of the board are heavily stitched underneath the thermal dissipation area. The copper is exposed in this area. To improve the thermal coupling between the module and the board I've used one of these: [https://quietpc.co.uk/gelid-gp-pads](https://quietpc.co.uk/gelid-gp-pads) (I think the 2mm one). In this case, minimising the distance between the rear plane of the module and the board is desirable; the thinner pads are going to have lower thermal resistance. Quectel actually advise the use of these too (*"In order to achieve a maximum performance while working under extended temperatures or extreme conditions (such as with maximum power or data rate) for a long time, it is strongly recommended to add a thermal pad or other thermally conductive compounds between the module and the main PCB for thermal dissipation."*)

> If possible, add a heatsink *on the top of the module*. In this case, A thermal pad should be used
between the heatsink and the module, and the heatsink should be designed with as many fins as possible to increase the heat dissipation area.
> Maximize airflow over/around the module.
> Use active cooling method when it is necessary to pull heat away from the module.

I found a heatsink on top of the module as advised provides good cooling. There's a 5V fan header on the board to permit active cooling too - Noctua make some nice 40mm 5V fans that work fine for this.

Other modules might work better with different cooling setups to the one Quectel describe though.

**Comment by mlinuxguy** [comment]
My use case for the RM500Q-AE is outside in an enclosure powered by POE++ so Summer heat of a few weeks at 45C will push the modem's heat dissipation.  Currently is 22C outside and modem is 36C (heat-sink on top only), previously inside the WG1608 with heatsink on top and bottom it would be 32C in same conditions.

The 3 ground layers under the board will help transmit the heat.  On the current USB 3.0 adapter I have I put a copper heatsink under the PCB contacting the metal case (no metal contacts under that area to short).

We've been discussing both yours and other designs on the Openwrt ROOter forum as these 5G modems need a LOT of power under load.

I really wish my towers would get upgraded so I could see some of your throughput....  I max out at 300mbps down due to my towers.  I'm using a RPI4 in its own heatsink case to drive the modem using ROOter software (branch of Openwrt)

Great design!  I may have to make one after I get this RM500Q stable... suffering from random TX hangs right now.  Got a case opened with Quectel.

**Comment by themainframe** [comment]
Ah, interesting. Mine's in my fairly-cold UK loftspace with a fan and a top-mounted heatsink so I don't think I've ever seen anything above 35ºC! I should certainly consider other environments though. I think the small size of the board is also probably a detriment when it comes to heat dissipation. These big 6 & 8 layer router boards probably sink out a lot more heat than my little breakout PCB!

Off-topic - but that's fascinating about the TX dropouts! I'm actually using the RM500Q-GL on Linux with the `qmi_wwan` driver and NetworkManager and I see the same thing.  Certain applications (especially ones that open a lot of TCP connections quickly, high volume of small packets) will cause the modem to lock up. The classic symptom is the conntrack table on the machine hosting the module just gets huge and the only resolution is a USB replug/`usbreset`. Does that sound like the issue you're suffering from? I upgraded firmware to `RM500QGLABR11A02M4G` and that made no difference so I just ended up writing a Python script to `usbreset` the module if it falls over 😫

**Comment by mlinuxguy** [comment]
It sounds very similar to my issues.  We now have 3 to 4 on the forum reporting the same issues with the RM500Q (AE or GL versions).   Here is a reference to my last post in the forum discussing what I was sending Quectel: https://forums.whirlpool.net.au/thread/3vx1k1r3?p=933#r18659

Quote: " The classic symptom is the conntrack table on the machine hosting the module just gets huge and the only resolution is a USB replug/usbreset"
Interesting because I did a "fix" for that which may have made my problem worse..
Here is my post: https://forums.whirlpool.net.au/thread/3vx1k1r3?p=925#r68872490
I did: 
cat /proc/sys/net/netfilter/nf_conntrack_max
16384
echo 160000 > /proc/sys/net/netfilter/nf_conntrack_max

**Comment by themainframe** [comment]
Yeah, I changed the conntrack size but it'll just get bigger and bigger as more TCP connections are attempted I think. I think the bloated conntrack size is a symptom rather than a cause. Here's what I ended up doing as a workaround: [https://gist.github.com/themainframe/d183f081dd6b8dc1eeee1b438f1754a2](https://gist.github.com/themainframe/d183f081dd6b8dc1eeee1b438f1754a2). Just added as a `systemd` service on the box hosting the module. I can check when it's restarted in the `systemd` journal then too.

It's funny because it can go days without needing a restart then have a terrible day with restarts required every few hours. I think it's just down to usage.

**Comment by mlinuxguy** [comment]
Exactly what I've seen.  Some days I could run 48 hours without an issue,  get the TX hang reboot and get them constantly every 10 minutes.   Then it clears up.   So some app doing a bunch of small TCP connections seems likely.  Identifying that will be tough... I have many devices in my house along with PC's and smart phones... who knows what's doing it.

I am in an email conversation with Quectel and have provided the QLog log files that lead up to the TX hang and post hang.  It doesn't matter if you are on this rev like me:
 AT+GMR
RM500QAEAAR11A02M4G
or the A01M4G earlier rev.  All show same issue.   The US FAE for them says he hasn't seen that before....

FYI:  running in 4G LTE mode does not see those issues.    That's how I run weeks without issue while waiting on Quectel to respond.   4G/5G mode and 5G SA are where I see it.

**Comment by themainframe** [comment]
Opening Blizzard's Battle.net app was almost always a sure-fire way to kill it in my experience. That's renowned for opening a million connections for their P2P patch downloading stuff.

**Comment by git6578** [comment]
Wild idea, what about immersion cooling the module with electrocool EC-120?

**Comment by mlinuxguy** [comment]
![rpiwan](https://user-images.githubusercontent.com/2716117/116009845-4f348a00-a5e1-11eb-8b71-b891e994bbf0.jpg)
That would probably work, but I'm all about fire-and-forget (i.e. outside and don't have to mess with it so all passive).

On the RM500Q-AE TX hang front I have some info from Quectel R&D.
They see no PDN IPV6 or IPV4 request in the decoded packets at the time of hang.  They asked me what the default T-mobile needs (IPV6),  I'm not sure what PDN "Themainframe" guy needs on his.   Haven't heard back if new firmware is in the future.

**Comment by themainframe** [comment]
Long time since I've posted an update sorry. I did a little bit of experimentation with USB to try and diagnose myself what causes these lockups. 

I actually did some USB captures on the system while operating normally and then capturing while deliberately causing a lockup (using [`wrk`](https://github.com/wg/wrk) to spam lots of TCP sockets works well). I'm not hugely knowledgeable about USB internals, but to my eye, what seems to happen during the lockup is the host machine spams 20-40 `USB_BULK in` transfer type requests to the modem of type `URB_SUBMIT`, and then the modem responds with an equal number of empty `URB_COMPLETE` type messages with status `-EPROTO` (`-71`). This process repeats forever and causes lots of bus activity.

There's nowhere near this level of traffic during idle periods when the system is operating normally (I.e. not locked-up).

I haven't put this in front of Quectel yet but I may take some time to post on the forum this evening.

Interesting mention of IPv6 - my mobile network (Three, UK) supports IPv6 (on my iPhone 12 Pro I get full dual-stack v6 & v4 addresses). I've tried absolutely everything to get the RM500Q-GL to provide IPv6 using ModemManager, but couldn't get it working.

**Comment by mlinuxguy** [comment]
I switched out to a 8gb RPI 4 running Rooter / GoldenOrb on 21.01 RC3 of
Openwrt and that solved all the problems with USB xmit / recv storms (newer
kernel?).  The errors I got were: xhci-mtk 1e1c0000.xhci: ERROR unknown
event type 37
My setup is outside under the eve of my roof in 2 outdoor enclosures:
RM500Q-AE in its carrier plus a giant ALU heatsink under it, a short USB
3.0 cable over to the other enclosure where the RPI is bolted to its giant
heatsink.  Survived outdoor temps of 45C just fine.

I really like the Rooter/Goldenorb software for the RPI 4 as it allows me
to configure an auto-reboot of the modem when it loses internet
connection.  It's pretty much setup and forget about it now, just every
once in a while during normal hours T-mobile does something to the tower
and it reboots (and I check the routers webpage to see what happened).
